###############################################################
######### Digitizer Settings for BgRT PET Subsystem ###########
###############################################################

#####Singles Digitizer Settings #######

# Adder_ provides an integrated pulse by summing up hits that occur in the same crystal
/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/insert                        adder

# Readout_ regroup pulses per block of crystals, provide total energy of all pulses
/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/insert                        readout
/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/readout/setDepth              4

# Energy Resolution_ simulates a Gaussian energy blurring
/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/insert                        energyResolution
/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/energyResolution/fwhm        0.15
/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/energyResolution/energyOfReference 511. keV

# Time or Temporal Resolution_ simulates a Gaussian time blurring
#/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/insert timeResolution
#/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/timeResolution/fwhm 1000 ps

# Energy Framing or Energy window
/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/insert                        energyFraming
/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/energyFraming/setMin      395. keV
/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/energyFraming/setMax            600. keV

# DEADTIME_ needs to be optimized manually by testing with several values between 250 ns and 350 ns
#/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/insert deadtime
#/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/deadtime/setDeadTime 300 ns
#/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/deadtime/setMode nonparalysable
#/gate/digitizerMgr/LSO/SinglesDigitizer/Singles/deadtime/chooseDTVolume LSO

######## Coincidence Sorter Digitizer Settings ###########

# Prompt or Total Coincidences
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setInputCollection Singles
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setWindow          4.9 ns
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setDepth 4
/gate/digitizerMgr/CoincidenceSorter/Coincidences/minSectorDifference 2
/gate/digitizerMgr/CoincidenceSorter/Coincidences/MultiplesPolicy    takeAllGoods
/gate/digitizerMgr/CoincidenceSorter/Coincidences/describe

# Delayed or Random Coincidences
/gate/digitizerMgr/name                            delay
/gate/digitizerMgr/insert                          CoincidenceSorter
/gate/digitizerMgr/CoincidenceSorter/delay/setInputCollection Singles
/gate/digitizerMgr/CoincidenceSorter/delay/setWindow                 4.9 ns
/gate/digitizerMgr/CoincidenceSorter/delay/setOffset                 100.0 ns
/gate/digitizerMgr/CoincidenceSorter/delay/setDepth 4
/gate/digitizerMgr/CoincidenceSorter/delay/minSectorDifference 2
/gate/digitizerMgr/CoincidenceSorter/delay/MultiplesPolicy          takeAllGoods
/gate/digitizerMgr/CoincidenceSorter/delay/describe

#####################
####### Final coincidences: Prompts plus Delays##############
#####################
#/gate/digitizerMgr/name finalCoinc
#/gate/digitizerMgr/insert CoincidenceDigitizer
#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/addInputCollection delay
#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/addInputCollection Coincidences
#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/describe

#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/insert deadtime
#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/deadtime/setDeadTime 9 ns
#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/deadtime/setMode paralysable

#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/insert buffer
#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/buffer/setBufferSize 64 B
#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/buffer/setReadFrequency 14 MHz
#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/buffer/setMode 0
#/gate/digitizerMgr/CoincidenceDigitizer/finalCoinc/buffer/describe

