# Global Stat

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/stat_1.txt



# Define root list-mode file output

/gate/output/root/enable
/gate/output/root/setFileName             output/pet_1
/gate/output/root/setRootHitFlag          0
/gate/output/root/setRootSinglesFlag      1
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setRootdelayFlag        1
/gate/output/root/setRootNtupleFlag       0

# Summary

/gate/output/summary/enable
/gate/output/summary/setFileName output/summary_1.txt
/gate/output/summary/addCollection Singles
/gate/output/summary/addCollection Coincidences
/gate/output/summary/addCollection Delay



