# Global Stat

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output1/stat.txt
#/gate/actor/stat/saveEveryNSeconds 60


# Define root list-mode file output

/gate/output/root/enable
/gate/output/root/setFileName             output1/pet
/gate/output/root/setRootHitFlag          0
/gate/output/root/setRootSinglesFlag      0
/gate/output/root/setRootCoincidencesFlag 1
/gate/output/root/setRootdelayFlag        1
/gate/output/root/setRootNtupleFlag       0

# Summary

/gate/output/summary/enable
/gate/output/summary/setFileName output1/summary.txt
/gate/output/summary/addCollection Singles
/gate/output/summary/addCollection Coincidences
/gate/output/summary/addCollection Delay



