/gate/physics/addPhysicsList emstandard_opt3

# High cut by default
/gate/physics/Gamma/SetCutInRegion      world 1.0 cm
/gate/physics/Electron/SetCutInRegion   world 1.0 cm
/gate/physics/Positron/SetCutInRegion   world 1.0 cm

# Cuts for particle in NEMACylinder
/gate/physics/Gamma/SetCutInRegion      phantom 1.0 mm
/gate/physics/Electron/SetCutInRegion   phantom 1.0 mm
/gate/physics/Positron/SetCutInRegion   phantom 1.0 mm

# Cuts for particle in LSO
/gate/physics/Gamma/SetCutInRegion      LSO 1.0 mm
/gate/physics/Electron/SetCutInRegion   LSO 1.0 mm
/gate/physics/Positron/SetCutInRegion   LSO 1.0 mm

/gate/physics/processList Enabled
/gate/physics/processList Initialized
