/gate/physics/addPhysicsList emstandard_opt4

# High cuts by default
/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

###########
# Cuts commands for NECR Calculation
###########
# Cuts for particle in NEMACylinder
#/gate/physics/Gamma/SetCutInRegion      phantom 0.1 mm
#/gate/physics/Electron/SetCutInRegion   phantom 0.1 mm
#/gate/physics/Positron/SetCutInRegion   phantom 0.1 mm

# Cuts for particle in hole region
#/gate/physics/Gamma/SetCutInRegion      hole 0.5 mm
#/gate/physics/Electron/SetCutInRegion   hole 0.5 mm
#/gate/physics/Positron/SetCutInRegion   hole 0.5 mm

# Cuts for particle in linear source interior 
#/gate/physics/Gamma/SetCutInRegion      linearSourceIn 0.1 mm
#/gate/physics/Electron/SetCutInRegion   linearSourceIn 0.1 mm
#/gate/physics/Positron/SetCutInRegion   linearSourceIn 0.1 mm

# Cuts for particle in linear source exterior
#/gate/physics/Gamma/SetCutInRegion      linearSourceOut 0.1 mm
#/gate/physics/Electron/SetCutInRegion   linearSourceOut 0.1 mm
#/gate/physics/Positron/SetCutInRegion   linearSourceOut 0.1 mm

##########
# Cut commands for sensitivity calculation
##########

# Cuts for particles in phantom
/gate/physics/Gamma/SetCutInRegion      phantom 0.1 mm
/gate/physics/Electron/SetCutInRegion   phantom 0.1 mm
/gate/physics/Positron/SetCutInRegion   phantom 0.1 mm

# Cuts for particle in aluminum sleeve 01
/gate/physics/Gamma/SetCutInRegion      layer1 0.1 mm
/gate/physics/Electron/SetCutInRegion   layer1 0.1 mm
/gate/physics/Positron/SetCutInRegion   layer1 0.1 mm

# Cuts for particle in aluminum sleeve 02
/gate/physics/Gamma/SetCutInRegion      layer2 0.1 mm
/gate/physics/Electron/SetCutInRegion   layer2 0.1 mm
/gate/physics/Positron/SetCutInRegion   layer2 0.1 mm

# Cuts for particle in LSO
/gate/physics/Gamma/SetCutInRegion      LSO 0.1 mm
/gate/physics/Electron/SetCutInRegion   LSO 0.1 mm
/gate/physics/Positron/SetCutInRegion   LSO 0.1 mm

#############

/gate/physics/processList Enabled
/gate/physics/processList Initialized
