# Source for Sensitivity Calculation 
/gate/source/addSource twogamma
/gate/source/twogamma/setActivity 4.0 MBq
/gate/source/twogamma/setForcedUnstableFlag true
/gate/source/twogamma/setForcedHalfLife 6586.0 s
/gate/source/twogamma/setType backtoback
/gate/source/twogamma/gps/particle gamma
/gate/source/twogamma/gps/energytype Mono
/gate/source/twogamma/gps/monoenergy 0.511 MeV
/gate/source/twogamma/gps/type Volume
/gate/source/twogamma/gps/shape         Cylinder
/gate/source/twogamma/gps/centre        0.0 0.0 0.0 mm
/gate/source/twogamma/gps/radius        1.0 mm
/gate/source/twogamma/gps/halfz         350 mm
/gate/source/twogamma/visualize  green

/gate/source/list
